language: go

go:
  - 1.8.x
  - 1.7.x

before_install:
  - mkdir $GOPATH/bin
  - wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.zip
  - unzip glide-v0.12.3-linux-amd64.zip
  - install linux-amd64/glide $GOPATH/bin/glide

install:
  - glide install

script: go test -v $(glide nv)
